### ISSUE TITLE
Iniciar projeto do frontend com React.js e Typescript (create-react-app); (path: src/frontend/)

### ISSUE THREAD

**Issue by eduhdm** [eduhdm/podcodar-platform#1]
stack:
Frontend: React.js/Typescript/Next.js PWA
Testes de unidade: Jest/Testing-library
Testes de integração: MirageJS (mock API)
Testes de sistema: Cypress
Linter: Eslint/Prettier

para componentes web vamos utilizar o material ui

**Comment by Victorams** [comment]
Issue resolvido na PR #3 .
